import type { CollectionConfig, FieldHook, Validate, Where } from 'payload'

import { mediaField, slugField } from '@/fields'
import { filterMeditationsByLocale } from '@/hooks/meditationHooks'
import { serverEnv } from '@/lib/env'
import { LOCALES } from '@/lib/locales'
import { getR2Url } from '@/lib/storage/r2NativeAdapter'
import { virtualUrlField } from '@/lib/storage/urlFields'
import { KeyframeData, KeyframeDefinition } from '@/types/frames'

/**
 * afterRead hook for the randomSongUrl virtual field.
 * Returns the URL of a random song tagged with the meditation's songTag.
 * Uses efficient count + random offset approach (2 queries).
 */
const randomSongUrlAfterRead: FieldHook = async ({ data, req }) => {
  const songTagId =
    typeof data?.songTag === 'object' && data?.songTag !== null ? data.songTag.id : data?.songTag
  if (!songTagId) return null

  const songWhere: Where = {
    tags: { in: [songTagId] },
    deletedAt: { exists: false },
  }

  const { totalDocs } = await req.payload.count({
    collection: 'songs',
    where: songWhere,
  })

  if (totalDocs === 0) return null

  const randomPage = Math.floor(Math.random() * totalDocs) + 1

  const { docs } = await req.payload.find({
    collection: 'songs',
    where: songWhere,
    select: { filename: true },
    limit: 1,
    page: randomPage,
    depth: 0,
  })

  const song = docs[0]
  if (!song?.filename) return null

  return getR2Url(song.filename) ?? `/api/songs/file/${song.filename}`
}

export const Meditations: CollectionConfig = {
  slug: 'meditations',
  trash: true,
  hooks: {
    beforeOperation: [filterMeditationsByLocale],
  },
  defaultPopulate: {
    randomSongUrl: false,
  },
  versions: {
    maxPerDoc: 3,
    drafts: {
      schedulePublish: true,
    },
  },
  upload: {
    staticDir: 'media/meditations',
    bulkUpload: false,
    hideRemoveFile: true,
    mimeTypes: ['audio/mpeg', 'audio/mp3', 'audio/aac', 'audio/ogg'],
  },
  admin: {
    group: 'Content',
    useAsTitle: 'label',
    defaultColumns: ['label', 'thumbnail', '_status', 'tags', 'durationMinutes'],
    livePreview: {
      url: ({ data }) => {
        const baseURL = serverEnv.WEMEDITATE_WEB_URL
        return `${baseURL}/${data.locale}/preview/embed?collection=meditations&id=${data.id}`
      },
      breakpoints: [
        {
          label: 'Mobile',
          name: 'mobile',
          width: 375,
          height: 667,
        },
      ],
    },
    components: {
      edit: {
        PublishButton: '@/components/admin/buttons/UpdateOnlyPublishButton',
        SaveDraftButton: '@/components/admin/buttons/NextStepButton',
        Upload: '@/components/admin/AudioUpload',
      },
    },
  },
  fields: [
    // Virtual URL field generated by factory function
    // See src/lib/storage/urlFields.ts for implementation details
    virtualUrlField({ collection: 'meditations', adapter: 'r2' }),
    {
      name: 'randomSongUrl',
      type: 'text',
      virtual: true,
      admin: { hidden: true },
      hooks: {
        afterRead: [randomSongUrlAfterRead],
      },
    },
    {
      type: 'tabs',
      tabs: [
        {
          label: 'Details',
          fields: [
            {
              name: 'label',
              type: 'text',
              label: 'Internal Name',
              required: true,
            },
            {
              name: 'locale',
              type: 'select',
              options: LOCALES.map((locale) => ({
                label: locale.label,
                value: locale.code,
              })),
              defaultValue: ({ locale }: { locale?: string }) => locale || 'en',
              required: true,
              admin: {
                hidden: true,
              },
              access: {
                update: () => false,
              },
            },
            {
              name: 'narrator',
              type: 'relationship',
              relationTo: 'narrators',
              required: true,
              admin: {
                description:
                  'This should be the name of the yogi who did the recording. We need this for dynamic followup audio clips. Cannot be changed after creation.',
              },
              access: {
                // Narrator can only be set during creation, not update
                // This simplifies frame caching since narrator won't change during editing
                // TODO: Updated should be disabled again once legacy meditations have had their narrator updated
                //update: () => false,
              },
              validate: ((value, options) => {
                // Only required during update
                const isUpdate = options.operation === 'update' || !!options.id
                if (isUpdate && !value) {
                  return 'Narrator is required'
                }
                return true
              }) as Validate,
            },
            {
              name: 'songTag',
              type: 'relationship',
              relationTo: 'song-tags',
              admin: {
                condition: ({ id }) => !!id,
                description: 'Music with this tag will be offered to the seeker',
                components: {
                  Field: '@/components/admin/TagSelector',
                },
              },
            },
            {
              name: 'fileMetadata',
              type: 'json',
              admin: {
                condition: ({ id }) => !!id,
                readOnly: true,
              },
            },
            {
              name: 'durationMinutes',
              type: 'number',
              label: 'Duration (minutes)',
              admin: {
                readOnly: true,
                hidden: true,
              },
              hooks: {
                afterRead: [
                  async ({ data }) => {
                    const metadata = data?.fileMetadata as { duration?: number } | null | undefined
                    if (metadata?.duration) {
                      return Math.round(metadata.duration / 60)
                    }
                    return null
                  },
                ],
              },
            },
          ],
        },
        {
          label: 'Publishing',
          admin: {
            condition: ({ id }) => !!id,
          },
          fields: [
            {
              name: 'title',
              type: 'text',
              label: 'Public Title',
              validate: ((value, options) => {
                // Only required during update
                const isUpdate = options.operation === 'update' || !!options.id
                if (isUpdate && !value) {
                  return 'Public Title is required'
                }
                return true
              }) as Validate,
            },
            slugField({ useAsSlug: 'title' }),
            {
              ...mediaField({
                name: 'thumbnail',
                required: false, // Conditionally required via validation
                tagName: 'meditation-thumbnail',
              }),
              validate: ((value, options) => {
                // Only required during update
                const isUpdate = options.operation === 'update' || !!options.id
                if (isUpdate && !value) {
                  return 'Thumbnail is required'
                }
                return true
              }) as Validate,
            },
            {
              name: 'type',
              type: 'select',
              required: true,
              defaultValue: 'quick',
              options: [
                { label: 'Quick', value: 'quick' },
                { label: 'Daily', value: 'daily' },
                { label: 'Path', value: 'lesson' },
              ],
              admin: {
                custom: {
                  descriptions: {
                    quick:
                      'Time-based meditations without personalization. Offered based on time of day.',
                    daily:
                      'Personalized meditations with interactive features. Offered based on seeker mood/state.',
                    lesson:
                      'Meditations that complement Path lessons. Not shown in daily recommendations.',
                  },
                },
                components: {
                  Field: '@/components/admin/ToggleGroupField',
                  Description: '@/components/admin/SelectDescription',
                },
              },
            },
            {
              name: 'timings',
              type: 'select',
              hasMany: true,
              options: [
                { label: 'Morning', value: 'morning' },
                { label: 'Afternoon', value: 'afternoon' },
                { label: 'Evening', value: 'evening' },
                { label: 'Night', value: 'night' },
              ],
              admin: {
                condition: (data) => data.type === 'quick' || data.type === 'daily',
                description: 'When this meditation is available',
                components: {
                  Field: '@/components/admin/ToggleGroupField',
                },
              },
            },
            {
              name: 'tags',
              type: 'relationship',
              relationTo: 'meditation-tags',
              hasMany: true,
              filterOptions: { isParent: { not_equals: true } },
              admin: {
                condition: (data) => data.type === 'daily',
                description: 'Categorize this meditation for seekers to find it',
                components: {
                  Field: '@/components/admin/TagSelector',
                },
                custom: {
                  filterQuery: { 'where[isParent][not_equals]': 'true' },
                  size: 'large',
                },
              },
            },
          ],
        },
        {
          label: 'Video',
          admin: {
            condition: ({ id }) => !!id,
          },
          fields: [
            {
              type: 'tabs',
              tabs: [
                {
                  label: 'Frames',
                  description: 'Remove or re-order frames',
                  fields: [
                    {
                      name: 'frames',
                      type: 'json',
                      admin: {
                        components: {
                          Field: '@/components/admin/FrameEditor/FrameListManager',
                        },
                      },
                      validate: ((value, options) => {
                        // Only required during update (not on create)
                        const isUpdate = options.operation === 'update' || !!options.id
                        if (isUpdate && (!value || !Array.isArray(value) || value.length === 0)) {
                          return 'At least one frame is required'
                        }
                        return true
                      }) as Validate,
                      hooks: {
                        beforeChange: [
                          async ({ value }) => {
                            if (!value || !Array.isArray(value)) return []

                            return value
                              .filter((v) => {
                                // Drop malformed frames silently
                                if (!v || typeof v !== 'object') return false
                                if (!v.id) return false
                                if (
                                  typeof v.timestamp !== 'number' ||
                                  v.timestamp < 0 ||
                                  isNaN(v.timestamp)
                                )
                                  return false
                                return true
                              })
                              .map(
                                (v) => ({ id: v.id, timestamp: v.timestamp }) as KeyframeDefinition,
                              )
                              .sort((a, b) => a.timestamp - b.timestamp)
                          },
                        ],
                        afterRead: [
                          async ({ value, req }) => {
                            if (!value || !Array.isArray(value)) return []
                            const frames = value as KeyframeData[]

                            const frameIds = frames.map((f) => f.id)
                            if (frameIds.length === 0) return []

                            try {
                              const frameDocs = await req.payload.find({
                                collection: 'frames',
                                where: { id: { in: frameIds } },
                                limit: frameIds.length,
                              })

                              // Create map of relevant frame data
                              const frameMap = Object.fromEntries(
                                frameDocs.docs.map((frame) => [frame.id, frame]),
                              )

                              // Add data to each frame and sort by timestamp
                              return frames.map((v) => {
                                return {
                                  ...v,
                                  ...frameMap[v.id],
                                  timestamp: Math.round(v.timestamp),
                                } as KeyframeData
                              })
                            } catch (error) {
                              // If frames have thumbnails that reference deleted media, gracefully skip frame enrichment
                              // This can happen during import operations with --reset when media is deleted
                              req.payload.logger.warn({
                                msg: 'Failed to enrich frame data for meditation',
                                frameCount: frames.length,
                                frameIds: frameIds.slice(0, 5), // Log first 5 IDs to avoid too much data
                                error: error instanceof Error ? error.message : String(error),
                              })

                              // Return basic frame data without enrichment
                              return frames.map((v) => ({
                                ...v,
                                timestamp: Math.round(v.timestamp),
                              })) as KeyframeData[]
                            }
                          },
                        ],
                      },
                    },
                  ],
                },
                {
                  label: 'Add New',
                  description: 'Add new frames to the meditation',
                  fields: [
                    {
                      name: 'frameInserter',
                      type: 'ui',
                      admin: {
                        components: {
                          Field: '@/components/admin/FrameEditor/FrameInserter',
                        },
                      },
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
}
