import type { CollectionConfig, Validate } from 'payload'

import { mediaField, slugField } from '@/fields'
import { trackClientUsageHook } from '@/jobs/tasks/TrackUsage'
import { LOCALES } from '@/lib/locales'
import { virtualUrlField } from '@/lib/storage/urlFields'
import { KeyframeData, KeyframeDefinition } from '@/types/frames'

export const Meditations: CollectionConfig = {
  slug: 'meditations',
  trash: true,
  versions: {
    maxPerDoc: 3,
    drafts: {
      schedulePublish: true,
    },
  },
  upload: {
    staticDir: 'media/meditations',
    bulkUpload: false,
    hideRemoveFile: true,
    mimeTypes: ['audio/mpeg', 'audio/mp3', 'audio/aac', 'audio/ogg'],
  },
  admin: {
    group: 'Content',
    useAsTitle: 'label',
    defaultColumns: ['label', 'thumbnail', '_status', 'tags', 'durationMinutes'],
    livePreview: {
      url: ({ data }) => {
        const baseURL = process.env.WEMEDITATE_WEB_URL || 'http://localhost:5173'
        return `${baseURL}/${data.locale}/preview?collection=meditations&id=${data.id}`
      },
    },
    components: {
      edit: {
        PublishButton: '@/components/admin/buttons/UpdateOnlyPublishButton',
        SaveDraftButton: '@/components/admin/buttons/NextStepButton',
      },
    },
  },
  hooks: {
    afterRead: [trackClientUsageHook],
  },
  fields: [
    // Virtual URL field generated by factory function
    // See src/lib/storage/urlFields.ts for implementation details
    virtualUrlField({ collection: 'meditations', adapter: 'r2' }),
    {
      type: 'tabs',
      tabs: [
        {
          label: 'Details',
          fields: [
            {
              name: 'label',
              type: 'text',
              label: 'Internal Name',
              required: true,
            },
            {
              name: 'locale',
              type: 'select',
              options: LOCALES.map((locale) => ({
                label: locale.label,
                value: locale.code,
              })),
              defaultValue: 'en',
              required: true,
            },
            {
              name: 'narrator',
              type: 'relationship',
              relationTo: 'narrators',
              required: true,
              admin: {
                description:
                  'This should be the name of the yogi who did the recording. We need this for dynamic followup audio clips.',
              },
              validate: ((value, options) => {
                // Only required during update
                const isUpdate = options.operation === 'update' || !!options.id
                if (isUpdate && !value) {
                  return 'Narrator is required'
                }
                return true
              }) as Validate,
            },
            {
              name: 'musicTag',
              type: 'relationship',
              relationTo: 'music-tags',
              admin: {
                condition: ({ id }) => !!id,
                description: 'Music with this tag will be offered to the seeker',
                components: {
                  Field: '@/components/admin/TagSelector',
                },
              },
            },
            {
              name: 'fileMetadata',
              type: 'json',
              admin: {
                condition: ({ id }) => !!id,
                readOnly: true,
              },
            },
            {
              name: 'durationMinutes',
              type: 'number',
              label: 'Duration (minutes)',
              admin: {
                readOnly: true,
                hidden: true,
              },
              hooks: {
                afterRead: [
                  async ({ data }) => {
                    const metadata = data?.fileMetadata as { duration?: number } | null | undefined
                    if (metadata?.duration) {
                      return Math.round(metadata.duration / 60)
                    }
                    return null
                  },
                ],
              },
            },
          ],
        },
        {
          label: 'Publishing',
          admin: {
            condition: ({ id }) => !!id,
          },
          fields: [
            {
              name: 'title',
              type: 'text',
              label: 'Public Title',
              validate: ((value, options) => {
                // Only required during update
                const isUpdate = options.operation === 'update' || !!options.id
                if (isUpdate && !value) {
                  return 'Public Title is required'
                }
                return true
              }) as Validate,
            },
            slugField({ useAsSlug: 'title' }),
            {
              ...mediaField({
                name: 'thumbnail',
                required: false, // Conditionally required via validation
                tagName: 'meditation-thumbnail',
              }),
              validate: ((value, options) => {
                // Only required during update
                const isUpdate = options.operation === 'update' || !!options.id
                if (isUpdate && !value) {
                  return 'Thumbnail is required'
                }
                return true
              }) as Validate,
            },
            {
              name: 'tags',
              type: 'relationship',
              relationTo: 'meditation-tags',
              hasMany: true,
              admin: {
                description: 'Categorize this meditation for seekers to find it',
                components: {
                  Field: '@/components/admin/TagSelector',
                },
                custom: {
                  size: 'large',
                },
              },
            },
          ],
        },
        {
          label: 'Video',
          admin: {
            condition: ({ id }) => !!id,
          },
          fields: [
            {
              type: 'tabs',
              tabs: [
                {
                  label: 'Manage',
                  description: 'Edit frame timestamps and order',
                  fields: [
                    {
                      name: 'frames',
                      type: 'json',
                      admin: {
                        components: {
                          Field: '@/components/admin/FrameEditor/FrameListManager',
                        },
                      },
                      validate: ((value, options) => {
                        // Only required during update (not on create)
                        const isUpdate = options.operation === 'update' || !!options.id
                        if (isUpdate && (!value || !Array.isArray(value) || value.length === 0)) {
                          return 'At least one frame is required'
                        }
                        return true
                      }) as Validate,
                      hooks: {
                        beforeChange: [
                          async ({ value }) => {
                            if (!value || !Array.isArray(value)) return []

                            return value
                              .filter((v) => {
                                // Drop malformed frames silently
                                if (!v || typeof v !== 'object') return false
                                if (!v.id) return false
                                if (
                                  typeof v.timestamp !== 'number' ||
                                  v.timestamp < 0 ||
                                  isNaN(v.timestamp)
                                )
                                  return false
                                return true
                              })
                              .map(
                                (v) => ({ id: v.id, timestamp: v.timestamp }) as KeyframeDefinition,
                              )
                              .sort((a, b) => a.timestamp - b.timestamp)
                          },
                        ],
                        afterRead: [
                          async ({ value, req }) => {
                            if (!value || !Array.isArray(value)) return []
                            const frames = value as KeyframeData[]

                            const frameIds = frames.map((f) => f.id)
                            if (frameIds.length === 0) return []

                            try {
                              const frameDocs = await req.payload.find({
                                collection: 'frames',
                                where: { id: { in: frameIds } },
                                limit: frameIds.length,
                              })

                              // Create map of relevant frame data
                              const frameMap = Object.fromEntries(
                                frameDocs.docs.map((frame) => [frame.id, frame]),
                              )

                              // Add data to each frame and sort by timestamp
                              return frames.map((v) => {
                                return {
                                  ...v,
                                  ...frameMap[v.id],
                                  timestamp: Math.round(v.timestamp),
                                } as KeyframeData
                              })
                            } catch (error) {
                              // If frames have thumbnails that reference deleted media, gracefully skip frame enrichment
                              // This can happen during import operations with --reset when media is deleted
                              req.payload.logger.warn({
                                msg: 'Failed to enrich frame data for meditation',
                                frameCount: frames.length,
                                frameIds: frameIds.slice(0, 5), // Log first 5 IDs to avoid too much data
                                error: error instanceof Error ? error.message : String(error),
                              })

                              // Return basic frame data without enrichment
                              return frames.map((v) => ({
                                ...v,
                                timestamp: Math.round(v.timestamp),
                              })) as KeyframeData[]
                            }
                          },
                        ],
                      },
                    },
                  ],
                },
                {
                  label: 'Insert',
                  description: 'Browse and add new frames',
                  fields: [
                    {
                      name: 'frameInserter',
                      type: 'ui',
                      admin: {
                        components: {
                          Field: '@/components/admin/FrameEditor/FrameInserter',
                        },
                      },
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
}
