import os from 'os'
import path from 'path'

import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths'
import { defineConfig } from 'vitest/config'

import { DEFAULT_TEST_DATABASE_URL } from './tests/utils/postgresTestPool'

const sharedResolve = {
  alias: {
    '@': path.resolve(__dirname, './src'),
    tests: path.resolve(__dirname, './tests'),
  },
}

const sharedPlugins = [tsconfigPaths(), react()]

// Shared across both Vitest projects (unit + int) — previously copy-pasted in
// each project's `env` block (see #499 §6). DATABASE_URL falls back to a local
// Postgres for contributors who don't set it; CI injects the service-container URL.
const sharedTestEnv: Record<string, string> = {
  NODE_ENV: 'test',
  DATABASE_URL: process.env.DATABASE_URL ?? DEFAULT_TEST_DATABASE_URL,
  PAYLOAD_SECRET: 'test-secret-key-with-32-chars-minimum',
  SAHAJCLOUD_PREVIEW_SECRET: 'test-preview-secret-32-chars',
  WEMEDITATE_WEB_URL: 'http://localhost:5173',
  SAHAJATLAS_URL: 'http://localhost:5174',
  NIRMALA_VIDYA_API_KEY: 'test-nirmala-vidya-api-key-placeholder',
}

// Upper bound on concurrent integration-suite forks (#499 §2). The int lane is
// DB-bound: every suite runs a full-schema Drizzle `push` against the SAME
// Postgres, and each Payload instance opens a connection pool (node-pg default
// max 10). So forks are capped to keep total connections well under Postgres'
// default max_connections (100) and to leave the dev machine headroom locally
// (the CPU-guard rule in docs/rules/testing-reqs.md). CI gets a dedicated
// service-container Postgres, so it can use the (smaller) runner fully. Override
// with VITEST_INT_MAX_FORKS.
// V8 coverage instruments the whole Payload module graph, which makes the
// per-suite bootstrap (buildConfig + getPayload + Drizzle push) several× slower —
// enough to blow the normal 60s/120s timeouts. `pnpm test:coverage` is an
// opt-in, heavyweight run (≈20 min), so grant it much larger (600s) timeouts.
// Detected from argv since Vitest doesn't expose the coverage flag in config.
const isCoverage = process.argv.includes('--coverage')

const cpuCount = os.availableParallelism?.() ?? os.cpus().length
const envMaxForks = Number(process.env.VITEST_INT_MAX_FORKS)
const intMaxForks =
  Number.isFinite(envMaxForks) && envMaxForks >= 1
    ? Math.floor(envMaxForks) // explicit override (ignored if non-numeric/<1)
    : process.env.CI
      ? Math.min(cpuCount, 4)
      : Math.max(2, Math.min(cpuCount - 1, 6))

export default defineConfig({
  test: {
    css: {
      modules: {
        classNameStrategy: 'non-scoped',
      },
    },
    // Coverage for the unit + int lanes (#499 §3): `pnpm test:coverage` (no
    // --project → all projects). Off by default; CI's `pnpm test` stays
    // coverage-free. Thresholds are scoped to the security-critical access plugin
    // only (a soft signal, not a global gate) per the "test custom logic" rule.
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      reportsDirectory: './coverage',
      // Still emit the report if a test fails — under heavy v8 instrumentation a
      // slow Payload suite can occasionally trip a timeout, and we don't want one
      // flake to swallow the whole coverage report.
      reportOnFailure: true,
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/payload-types.ts', // generated by `pnpm generate:types`
        'src/migrations/**', // generated migrations
        '**/*.d.ts',
      ],
      thresholds: {
        // Soft signal on the security-critical access plugin ONLY — not a global
        // gate (aligns with the "test custom logic, not Payload internals" rule).
        // Set comfortably below current coverage (~68% stmts / 67% branches via
        // role-based-access alone) so it flags a regression without bit-rotting;
        // raise as access coverage improves.
        'src/plugins/access/**': {
          statements: 55,
          branches: 50,
          functions: 60,
          lines: 55,
        },
      },
    },
    projects: [
      {
        plugins: sharedPlugins,
        resolve: sharedResolve,
        test: {
          name: 'unit',
          environment: 'node',
          include: ['tests/unit/**/*.spec.ts'],
          testTimeout: 5000,
          env: sharedTestEnv,
        },
      },
      {
        plugins: sharedPlugins,
        resolve: sharedResolve,
        test: {
          name: 'int',
          environment: 'node',
          setupFiles: ['./vitest.setup.ts'],
          globalSetup: ['./tests/setup/globalSetup.ts'],
          include: ['tests/int/**/*.int.spec.ts', 'seeds/**/*.test.ts'],
          pool: 'forks',
          // File-level parallelism is EXPLICIT (#499 §2). `maxConcurrency: 1`
          // only serialises tests *within* a file — it does NOT serialise files.
          // `fileParallelism: true` (Vitest's default for the forks pool, pinned
          // here so it's not silently flipped) runs suites concurrently across
          // forked workers, bounded by `poolOptions.forks.maxForks` (see
          // `intMaxForks` above for the DB-connection rationale).
          maxConcurrency: 1,
          fileParallelism: true,
          poolOptions: {
            forks: {
              minForks: 1,
              maxForks: intMaxForks,
            },
          },
          // Postgres has real per-op latency (vs the old instant in-memory SQLite),
          // so write-heavy integration tests + per-suite schema push need more
          // headroom — and much more again under coverage instrumentation.
          testTimeout: isCoverage ? 600000 : 60000,
          hookTimeout: isCoverage ? 600000 : 120000,
          // One retry in CI only (#499 §5) — absorbs transient Postgres latency /
          // connection blips under the parallel load above (Playwright already
          // uses retries: 2 in CI). Local stays at 0 so failures are honest
          // during development.
          retry: process.env.CI ? 1 : 0,
          env: sharedTestEnv,
        },
      },
    ],
  },
})
