import type { CollectionConfig } from 'payload'

import { trackClientUsageHook } from '@/jobs/tasks/TrackUsage'
import { roleBasedAccess } from '@/lib/accessControl'
import { FRAME_CATEGORY_OPTIONS, GENDER_OPTIONS } from '@/lib/data'
import { handleProjectVisibility } from '@/lib/projectVisibility'
import { previewUrlField, streamMp4UrlField } from '@/lib/storage/urlFields'

export const Frames: CollectionConfig = {
  labels: {
    plural: 'Meditation Frames',
    singular: 'Meditation Frame',
  },
  slug: 'frames',
  access: roleBasedAccess('frames'),
  indexes: [
    {
      fields: ['imageSet'],
    },
  ],
  endpoints: [
    {
      path: '/by-narrator/:narratorId',
      method: 'get',
      handler: async (req) => {
        const narratorId = req.routeParams?.narratorId as string

        if (!narratorId) {
          return Response.json({ error: 'Narrator ID required' }, { status: 400 })
        }

        // Look up narrator to get gender
        const narrator = await req.payload.findByID({
          collection: 'narrators',
          id: narratorId,
          depth: 0,
        })

        if (!narrator) {
          return Response.json({ error: 'Narrator not found' }, { status: 404 })
        }

        // Get frames filtered by narrator's gender (imageSet)
        const frames = await req.payload.find({
          collection: 'frames',
          where: { imageSet: { equals: narrator.gender } },
          limit: 100,
          depth: 0,
        })

        return Response.json(frames)
      },
    },
  ],
  upload: {
    staticDir: 'media/frames',
    hideRemoveFile: true,
    mimeTypes: [
      // Images
      'image/jpeg',
      'image/jpg',
      'image/png',
      'image/webp',
      // Videos
      'video/mp4',
      'video/webm',
    ],
    // imageSizes removed - using Cloudflare Images flexible variants and Stream thumbnails
  },
  admin: {
    hidden: handleProjectVisibility('frames', ['wemeditate-app']),
    group: 'Resources',
    useAsTitle: 'filename',
    defaultColumns: ['category', 'tags', 'previewUrl', 'imageSet'],
    groupBy: true,
  },
  hooks: {
    // Filename handling is done directly in storage adapters:
    // - Cloudflare Images/Stream adapters update data.filename to the service-generated ID
    // - No collection-level hooks needed for filename management
    afterRead: [trackClientUsageHook],
  },
  fields: [
    // Virtual URL fields generated by factory functions
    // See src/lib/storage/urlFields.ts for implementation details
    previewUrlField({ collection: 'frames' }),
    streamMp4UrlField({ collection: 'frames' }),
    {
      name: 'imageSet',
      type: 'select',
      options: GENDER_OPTIONS,
      required: true,
    },
    {
      name: 'category',
      type: 'select',
      options: [...FRAME_CATEGORY_OPTIONS],
      required: true,
    },
    {
      name: 'tags',
      type: 'select',
      hasMany: true,
      options: [
        { label: 'Anahat', value: 'anahat' },
        { label: 'Back', value: 'back' },
        { label: 'Bandhan', value: 'bandhan' },
        { label: 'Both Hands', value: 'both hands' },
        { label: 'Center', value: 'center' },
        { label: 'Channel', value: 'channel' },
        { label: 'Earth', value: 'earth' },
        { label: 'Ego', value: 'ego' },
        { label: 'Feel', value: 'feel' },
        { label: 'Ham Ksham', value: 'ham ksham' },
        { label: 'Hamsa', value: 'hamsa' },
        { label: 'Hand', value: 'hand' },
        { label: 'Hands', value: 'hands' },
        { label: 'Ida', value: 'ida' },
        { label: 'Left', value: 'left' },
        { label: 'Left Handed', value: 'lefthanded' },
        { label: 'Massage', value: 'massage' },
        { label: 'Pingala', value: 'pingala' },
        { label: 'Raise', value: 'raise' },
        { label: 'Right', value: 'right' },
        { label: 'Right Handed', value: 'righthanded' },
        { label: 'Rising', value: 'rising' },
        { label: 'Silent', value: 'silent' },
        { label: 'Superego', value: 'superego' },
        { label: 'Tapping', value: 'tapping' },
      ],
    },
    {
      // Removed: thumbnail FileAttachmentField (replaced by thumbnailUrl virtual field from Cloudflare Stream)
      name: 'duration',
      type: 'number',
      hooks: {
        afterRead: [
          async ({ data }) => {
            return data &&
              typeof data.fileMetadata === 'object' &&
              typeof data.fileMetadata.duration === 'number'
              ? Math.round(data.fileMetadata.duration)
              : undefined
          },
        ],
      },
    },
    {
      name: 'fileMetadata',
      type: 'json',
      defaultValue: {},
      admin: {
        position: 'sidebar',
        readOnly: true,
      },
    },
  ],
}
