import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`app_cards\` ADD \`default_aspect_ratio\` text DEFAULT 'square';`)
  await db.run(sql`ALTER TABLE \`app_cards\` ADD \`default_text_color\` text DEFAULT 'black';`)
  await db.run(sql`ALTER TABLE \`app_cards\` ADD \`starting_soon_aspect_ratio\` text DEFAULT 'square';`)
  await db.run(sql`ALTER TABLE \`app_cards\` ADD \`starting_soon_text_color\` text DEFAULT 'black';`)
  await db.run(sql`ALTER TABLE \`app_cards\` ADD \`live_now_aspect_ratio\` text DEFAULT 'square';`)
  await db.run(sql`ALTER TABLE \`app_cards\` ADD \`live_now_text_color\` text DEFAULT 'black';`)
  await db.run(sql`ALTER TABLE \`app_cards\` DROP COLUMN \`default_overlay\`;`)
  await db.run(sql`ALTER TABLE \`app_cards\` DROP COLUMN \`starting_soon_overlay\`;`)
  await db.run(sql`ALTER TABLE \`app_cards\` DROP COLUMN \`live_now_overlay\`;`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` ADD \`version_default_aspect_ratio\` text DEFAULT 'square';`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` ADD \`version_default_text_color\` text DEFAULT 'black';`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` ADD \`version_starting_soon_aspect_ratio\` text DEFAULT 'square';`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` ADD \`version_starting_soon_text_color\` text DEFAULT 'black';`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` ADD \`version_live_now_aspect_ratio\` text DEFAULT 'square';`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` ADD \`version_live_now_text_color\` text DEFAULT 'black';`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` DROP COLUMN \`version_default_overlay\`;`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` DROP COLUMN \`version_starting_soon_overlay\`;`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` DROP COLUMN \`version_live_now_overlay\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_welcome\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_name\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_greeting\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_user_type\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_carousel\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_consent_modal\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`daily_main\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`daily_common\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`daily_load_info\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`path_overview\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`path_info\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`path_step_1\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`path_step_2\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`path_step_3\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`path_step_4\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`path_step_complete\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`explore_overview\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`explore_subtle_system\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`explore_talks_intro\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`explore_talks_list\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`explore_talks_player\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`profile_main\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`profile_favourites\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`profile_history\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`profile_account\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`profile_privacy_advertising\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`profile_contact\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`meditation_intent\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`meditation_reminder\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`meditation_footsoak\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`meditation_player\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`meditation_vibes_check\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`meditation_feedback\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`auth_common\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`auth_login\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`auth_restore_password\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`auth_restore_password_email_sent\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`auth_create_account\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`navigation\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`general\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`daily\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`path\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`explore\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`profile\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`meditation\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_welcome\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_name\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_greeting\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_user_type\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_carousel\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_consent_modal\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_daily_main\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_daily_common\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_daily_load_info\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_path_overview\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_path_info\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_path_step_1\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_path_step_2\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_path_step_3\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_path_step_4\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_path_step_complete\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_explore_overview\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_explore_subtle_system\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_explore_talks_intro\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_explore_talks_list\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_explore_talks_player\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_profile_main\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_profile_favourites\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_profile_history\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_profile_account\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_profile_privacy_advertising\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_profile_contact\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_meditation_intent\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_meditation_reminder\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_meditation_footsoak\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_meditation_player\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_meditation_vibes_check\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_meditation_feedback\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_auth_common\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_auth_login\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_auth_restore_password\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_auth_restore_password_email_sent\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_auth_create_account\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_navigation\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_general\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_daily\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_path\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_explore\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_profile\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_meditation\`;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`app_cards\` ADD \`default_overlay\` integer DEFAULT false;`)
  await db.run(sql`ALTER TABLE \`app_cards\` ADD \`starting_soon_overlay\` integer DEFAULT false;`)
  await db.run(sql`ALTER TABLE \`app_cards\` ADD \`live_now_overlay\` integer DEFAULT false;`)
  await db.run(sql`ALTER TABLE \`app_cards\` DROP COLUMN \`default_aspect_ratio\`;`)
  await db.run(sql`ALTER TABLE \`app_cards\` DROP COLUMN \`default_text_color\`;`)
  await db.run(sql`ALTER TABLE \`app_cards\` DROP COLUMN \`starting_soon_aspect_ratio\`;`)
  await db.run(sql`ALTER TABLE \`app_cards\` DROP COLUMN \`starting_soon_text_color\`;`)
  await db.run(sql`ALTER TABLE \`app_cards\` DROP COLUMN \`live_now_aspect_ratio\`;`)
  await db.run(sql`ALTER TABLE \`app_cards\` DROP COLUMN \`live_now_text_color\`;`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` ADD \`version_default_overlay\` integer DEFAULT false;`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` ADD \`version_starting_soon_overlay\` integer DEFAULT false;`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` ADD \`version_live_now_overlay\` integer DEFAULT false;`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` DROP COLUMN \`version_default_aspect_ratio\`;`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` DROP COLUMN \`version_default_text_color\`;`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` DROP COLUMN \`version_starting_soon_aspect_ratio\`;`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` DROP COLUMN \`version_starting_soon_text_color\`;`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` DROP COLUMN \`version_live_now_aspect_ratio\`;`)
  await db.run(sql`ALTER TABLE \`_app_cards_v\` DROP COLUMN \`version_live_now_text_color\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`daily\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`path\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`explore\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`profile\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`meditation\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_welcome\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_name\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_greeting\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_user_type\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_carousel\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_consent_modal\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`daily_main\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`daily_common\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`daily_load_info\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`path_overview\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`path_info\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`path_step_1\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`path_step_2\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`path_step_3\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`path_step_4\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`path_step_complete\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`explore_overview\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`explore_subtle_system\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`explore_talks_intro\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`explore_talks_list\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`explore_talks_player\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`profile_main\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`profile_favourites\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`profile_history\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`profile_account\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`profile_privacy_advertising\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`profile_contact\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`meditation_intent\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`meditation_reminder\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`meditation_footsoak\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`meditation_player\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`meditation_vibes_check\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`meditation_feedback\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`auth_common\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`auth_login\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`auth_restore_password\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`auth_restore_password_email_sent\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`auth_create_account\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`navigation\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`general\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_daily\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_path\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_explore\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_profile\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_meditation\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_welcome\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_name\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_greeting\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_user_type\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_carousel\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_consent_modal\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_daily_main\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_daily_common\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_daily_load_info\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_path_overview\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_path_info\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_path_step_1\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_path_step_2\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_path_step_3\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_path_step_4\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_path_step_complete\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_explore_overview\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_explore_subtle_system\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_explore_talks_intro\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_explore_talks_list\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_explore_talks_player\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_profile_main\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_profile_favourites\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_profile_history\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_profile_account\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_profile_privacy_advertising\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_profile_contact\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_meditation_intent\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_meditation_reminder\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_meditation_footsoak\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_meditation_player\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_meditation_vibes_check\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_meditation_feedback\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_auth_common\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_auth_login\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_auth_restore_password\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_auth_restore_password_email_sent\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_auth_create_account\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_navigation\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_general\`;`)
}
