import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`wm_web_translations\` ADD \`_status\` text DEFAULT 'draft';`)
  await db.run(sql`CREATE INDEX \`wm_web_translations__status_idx\` ON \`wm_web_translations\` (\`_status\`);`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v\` ADD \`version__status\` text DEFAULT 'draft';`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v\` ADD \`snapshot\` integer;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v\` ADD \`published_locale\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v\` ADD \`latest\` integer;`)
  await db.run(sql`CREATE INDEX \`_wm_web_translations_v_version_version__status_idx\` ON \`_wm_web_translations_v\` (\`version__status\`);`)
  await db.run(sql`CREATE INDEX \`_wm_web_translations_v_snapshot_idx\` ON \`_wm_web_translations_v\` (\`snapshot\`);`)
  await db.run(sql`CREATE INDEX \`_wm_web_translations_v_published_locale_idx\` ON \`_wm_web_translations_v\` (\`published_locale\`);`)
  await db.run(sql`CREATE INDEX \`_wm_web_translations_v_latest_idx\` ON \`_wm_web_translations_v\` (\`latest\`);`)
  await db.run(sql`ALTER TABLE \`wm_app_translations\` ADD \`_status\` text DEFAULT 'draft';`)
  await db.run(sql`CREATE INDEX \`wm_app_translations__status_idx\` ON \`wm_app_translations\` (\`_status\`);`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v\` ADD \`version__status\` text DEFAULT 'draft';`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v\` ADD \`snapshot\` integer;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v\` ADD \`published_locale\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v\` ADD \`latest\` integer;`)
  await db.run(sql`CREATE INDEX \`_wm_app_translations_v_version_version__status_idx\` ON \`_wm_app_translations_v\` (\`version__status\`);`)
  await db.run(sql`CREATE INDEX \`_wm_app_translations_v_snapshot_idx\` ON \`_wm_app_translations_v\` (\`snapshot\`);`)
  await db.run(sql`CREATE INDEX \`_wm_app_translations_v_published_locale_idx\` ON \`_wm_app_translations_v\` (\`published_locale\`);`)
  await db.run(sql`CREATE INDEX \`_wm_app_translations_v_latest_idx\` ON \`_wm_app_translations_v\` (\`latest\`);`)
  await db.run(sql`ALTER TABLE \`sy_atlas_translations\` ADD \`_status\` text DEFAULT 'draft';`)
  await db.run(sql`CREATE INDEX \`sy_atlas_translations__status_idx\` ON \`sy_atlas_translations\` (\`_status\`);`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v\` ADD \`version__status\` text DEFAULT 'draft';`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v\` ADD \`snapshot\` integer;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v\` ADD \`published_locale\` text;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v\` ADD \`latest\` integer;`)
  await db.run(sql`CREATE INDEX \`_sy_atlas_translations_v_version_version__status_idx\` ON \`_sy_atlas_translations_v\` (\`version__status\`);`)
  await db.run(sql`CREATE INDEX \`_sy_atlas_translations_v_snapshot_idx\` ON \`_sy_atlas_translations_v\` (\`snapshot\`);`)
  await db.run(sql`CREATE INDEX \`_sy_atlas_translations_v_published_locale_idx\` ON \`_sy_atlas_translations_v\` (\`published_locale\`);`)
  await db.run(sql`CREATE INDEX \`_sy_atlas_translations_v_latest_idx\` ON \`_sy_atlas_translations_v\` (\`latest\`);`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`DROP INDEX \`wm_web_translations__status_idx\`;`)
  await db.run(sql`ALTER TABLE \`wm_web_translations\` DROP COLUMN \`_status\`;`)
  await db.run(sql`DROP INDEX \`_wm_web_translations_v_version_version__status_idx\`;`)
  await db.run(sql`DROP INDEX \`_wm_web_translations_v_snapshot_idx\`;`)
  await db.run(sql`DROP INDEX \`_wm_web_translations_v_published_locale_idx\`;`)
  await db.run(sql`DROP INDEX \`_wm_web_translations_v_latest_idx\`;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v\` DROP COLUMN \`version__status\`;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v\` DROP COLUMN \`snapshot\`;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v\` DROP COLUMN \`published_locale\`;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v\` DROP COLUMN \`latest\`;`)
  await db.run(sql`DROP INDEX \`wm_app_translations__status_idx\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations\` DROP COLUMN \`_status\`;`)
  await db.run(sql`DROP INDEX \`_wm_app_translations_v_version_version__status_idx\`;`)
  await db.run(sql`DROP INDEX \`_wm_app_translations_v_snapshot_idx\`;`)
  await db.run(sql`DROP INDEX \`_wm_app_translations_v_published_locale_idx\`;`)
  await db.run(sql`DROP INDEX \`_wm_app_translations_v_latest_idx\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v\` DROP COLUMN \`version__status\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v\` DROP COLUMN \`snapshot\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v\` DROP COLUMN \`published_locale\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v\` DROP COLUMN \`latest\`;`)
  await db.run(sql`DROP INDEX \`sy_atlas_translations__status_idx\`;`)
  await db.run(sql`ALTER TABLE \`sy_atlas_translations\` DROP COLUMN \`_status\`;`)
  await db.run(sql`DROP INDEX \`_sy_atlas_translations_v_version_version__status_idx\`;`)
  await db.run(sql`DROP INDEX \`_sy_atlas_translations_v_snapshot_idx\`;`)
  await db.run(sql`DROP INDEX \`_sy_atlas_translations_v_published_locale_idx\`;`)
  await db.run(sql`DROP INDEX \`_sy_atlas_translations_v_latest_idx\`;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v\` DROP COLUMN \`version__status\`;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v\` DROP COLUMN \`snapshot\`;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v\` DROP COLUMN \`published_locale\`;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v\` DROP COLUMN \`latest\`;`)
}
