import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`wm_web_translations_locales\` ADD \`common\` text;`)
  await db.run(sql`ALTER TABLE \`wm_web_translations_locales\` ADD \`navigation\` text;`)
  await db.run(sql`ALTER TABLE \`wm_web_translations_locales\` DROP COLUMN \`strings\`;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v_locales\` ADD \`version_common\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v_locales\` ADD \`version_navigation\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v_locales\` DROP COLUMN \`version_strings\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`daily\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`path\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`explore\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`profile\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`meditation\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`strings\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_daily\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_path\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_explore\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_profile\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_meditation\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_strings\`;`)
  await db.run(sql`ALTER TABLE \`sy_atlas_translations_locales\` ADD \`common\` text;`)
  await db.run(sql`ALTER TABLE \`sy_atlas_translations_locales\` ADD \`map\` text;`)
  await db.run(sql`ALTER TABLE \`sy_atlas_translations_locales\` ADD \`location\` text;`)
  await db.run(sql`ALTER TABLE \`sy_atlas_translations_locales\` DROP COLUMN \`strings\`;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v_locales\` ADD \`version_common\` text;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v_locales\` ADD \`version_map\` text;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v_locales\` ADD \`version_location\` text;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v_locales\` DROP COLUMN \`version_strings\`;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`wm_web_translations_locales\` ADD \`strings\` text;`)
  await db.run(sql`ALTER TABLE \`wm_web_translations_locales\` DROP COLUMN \`common\`;`)
  await db.run(sql`ALTER TABLE \`wm_web_translations_locales\` DROP COLUMN \`navigation\`;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v_locales\` ADD \`version_strings\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v_locales\` DROP COLUMN \`version_common\`;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v_locales\` DROP COLUMN \`version_navigation\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`strings\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`daily\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`path\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`explore\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`profile\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`meditation\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_strings\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_daily\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_path\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_explore\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_profile\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_meditation\`;`)
  await db.run(sql`ALTER TABLE \`sy_atlas_translations_locales\` ADD \`strings\` text;`)
  await db.run(sql`ALTER TABLE \`sy_atlas_translations_locales\` DROP COLUMN \`common\`;`)
  await db.run(sql`ALTER TABLE \`sy_atlas_translations_locales\` DROP COLUMN \`map\`;`)
  await db.run(sql`ALTER TABLE \`sy_atlas_translations_locales\` DROP COLUMN \`location\`;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v_locales\` ADD \`version_strings\` text;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v_locales\` DROP COLUMN \`version_common\`;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v_locales\` DROP COLUMN \`version_map\`;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v_locales\` DROP COLUMN \`version_location\`;`)
}
