import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`videos\` ADD \`url\` text;`)
  await db.run(sql`ALTER TABLE \`wm_web_translations_locales\` ADD \`last_reviewed_at\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v_locales\` ADD \`version_last_reviewed_at\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_welcome\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_user_type\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_carousel\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_consent_modal\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`profile_privacy_advertising\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`meditation_footsoak\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`auth_create_account\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_welcome_strings\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_user_type_strings\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_carousel_strings\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_consent_modal_strings\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`profile_privacy_advertising_strings\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`meditation_footsoak_strings\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`auth_create_account_strings\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_welcome\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_user_type\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_carousel\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_consent_modal\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_profile_privacy_advertising\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_meditation_footsoak\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_auth_create_account\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_welcome_strings\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_user_type_strings\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_carousel_strings\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_consent_modal_strings\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_profile_privacy_advertising_strings\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_meditation_footsoak_strings\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_auth_create_account_strings\`;`)
  await db.run(sql`ALTER TABLE \`sy_atlas_translations_locales\` ADD \`last_reviewed_at\` text;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v_locales\` ADD \`version_last_reviewed_at\` text;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_welcome_strings\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_user_type_strings\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_carousel_strings\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`onboarding_consent_modal_strings\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`profile_privacy_advertising_strings\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`meditation_footsoak_strings\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` ADD \`auth_create_account_strings\` text;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_welcome\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_user_type\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_carousel\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`onboarding_consent_modal\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`profile_privacy_advertising\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`meditation_footsoak\`;`)
  await db.run(sql`ALTER TABLE \`wm_app_translations_locales\` DROP COLUMN \`auth_create_account\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_welcome_strings\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_user_type_strings\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_carousel_strings\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_onboarding_consent_modal_strings\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_profile_privacy_advertising_strings\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_meditation_footsoak_strings\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` ADD \`version_auth_create_account_strings\` text;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_welcome\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_user_type\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_carousel\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_onboarding_consent_modal\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_profile_privacy_advertising\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_meditation_footsoak\`;`)
  await db.run(sql`ALTER TABLE \`_wm_app_translations_v_locales\` DROP COLUMN \`version_auth_create_account\`;`)
  await db.run(sql`ALTER TABLE \`videos\` DROP COLUMN \`url\`;`)
  await db.run(sql`ALTER TABLE \`wm_web_translations_locales\` DROP COLUMN \`last_reviewed_at\`;`)
  await db.run(sql`ALTER TABLE \`_wm_web_translations_v_locales\` DROP COLUMN \`version_last_reviewed_at\`;`)
  await db.run(sql`ALTER TABLE \`sy_atlas_translations_locales\` DROP COLUMN \`last_reviewed_at\`;`)
  await db.run(sql`ALTER TABLE \`_sy_atlas_translations_v_locales\` DROP COLUMN \`version_last_reviewed_at\`;`)
}
