/**
 * OpenAPI Specification Endpoint
 *
 * Filters the OpenAPI spec for client documentation, adding `x-internal: true`
 * markers to operations that should be hidden from the Scalar documentation UI.
 *
 * Supports project-based filtering via ?project= query parameter:
 * - No project: Shows all collections accessible by any client role
 * - ?project=wemeditate-web: Shows only We Meditate Web collections
 * - ?project=wemeditate-app: Shows only We Meditate App collections
 * - ?project=sahaj-atlas: Shows only Sahaj Atlas collections
 *
 * The raw spec is generated by payload-oapi at `/api/openapi-raw.json`.
 * This route fetches it, filters it, and returns the processed spec.
 */

import { NextRequest, NextResponse } from 'next/server'

import { filterSpec, type OpenAPISpec } from '@/lib/openapi/specFilter'
import { isValidProject, type ProjectSlug } from '@/lib/projects'

export async function GET(request: NextRequest) {
  try {
    // Parse project from query params
    const projectParam = request.nextUrl.searchParams.get('project')
    const project: ProjectSlug | null =
      projectParam && isValidProject(projectParam) ? (projectParam as ProjectSlug) : null

    // Get the base URL from the request
    const baseUrl = request.nextUrl.origin

    // Fetch the raw OpenAPI spec from payload-oapi with timeout
    const controller = new AbortController()
    const timeoutId = setTimeout(() => controller.abort(), 10000) // 10 second timeout

    const rawSpecResponse = await fetch(`${baseUrl}/api/openapi-raw.json`, {
      headers: {
        // Forward relevant headers
        Accept: 'application/json',
      },
      signal: controller.signal,
    })

    clearTimeout(timeoutId)

    if (!rawSpecResponse.ok) {
      return NextResponse.json(
        { error: 'Failed to fetch OpenAPI specification' },
        { status: rawSpecResponse.status },
      )
    }

    const rawSpec = (await rawSpecResponse.json()) as OpenAPISpec

    // Filter spec using project-based filtering
    const filteredSpec = filterSpec(rawSpec, { project })

    return NextResponse.json(filteredSpec, {
      headers: {
        'Content-Type': 'application/json',
        // Allow caching for 5 minutes, vary by project parameter
        'Cache-Control': 'public, max-age=300',
        Vary: 'Accept',
      },
    })
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error('[OpenAPI] Error generating marked spec:', error)

    return NextResponse.json(
      { error: 'Internal server error while generating OpenAPI specification' },
      { status: 500 },
    )
  }
}
