/**
 * OpenAPI Specification Endpoint
 *
 * This route intercepts requests for the OpenAPI spec and adds `x-internal: true`
 * markers to operations that should be hidden from the Scalar documentation UI.
 *
 * Supports role-based filtering via ?role= query parameter:
 * - No role: Shows all collections accessible by any client role
 * - ?role=we-meditate-web: Shows only We Meditate Web collections
 * - ?role=we-meditate-app: Shows only We Meditate App collections
 * - ?role=sahaj-atlas: Shows only Sahaj Atlas collections
 *
 * The raw spec is generated by payload-oapi at `/api/openapi-raw.json`.
 * This route fetches it, marks internal paths, and returns the filtered spec.
 */

import { NextRequest, NextResponse } from 'next/server'

import { isValidClientRole } from '@/lib/openapi/filterByClientRole'
import { markInternalPaths, type OpenAPISpec } from '@/lib/openapi/markInternalPaths'
import type { ClientRole } from '@/types/roles'

export async function GET(request: NextRequest) {
  try {
    // Parse role from query params
    const roleParam = request.nextUrl.searchParams.get('role')
    const role: ClientRole | null =
      roleParam && isValidClientRole(roleParam) ? (roleParam as ClientRole) : null

    // Get the base URL from the request
    const baseUrl = request.nextUrl.origin

    // Fetch the raw OpenAPI spec from payload-oapi with timeout
    const controller = new AbortController()
    const timeoutId = setTimeout(() => controller.abort(), 10000) // 10 second timeout

    const rawSpecResponse = await fetch(`${baseUrl}/api/openapi-raw.json`, {
      headers: {
        // Forward relevant headers
        Accept: 'application/json',
      },
      signal: controller.signal,
    })

    clearTimeout(timeoutId)

    if (!rawSpecResponse.ok) {
      return NextResponse.json(
        { error: 'Failed to fetch OpenAPI specification' },
        { status: rawSpecResponse.status },
      )
    }

    const rawSpec = (await rawSpecResponse.json()) as OpenAPISpec

    // Mark internal paths using role-based filtering
    const markedSpec = markInternalPaths(rawSpec, { role })

    return NextResponse.json(markedSpec, {
      headers: {
        'Content-Type': 'application/json',
        // Allow caching for 5 minutes, vary by role parameter
        'Cache-Control': 'public, max-age=300',
        Vary: 'Accept',
      },
    })
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error('[OpenAPI] Error generating marked spec:', error)

    return NextResponse.json(
      { error: 'Internal server error while generating OpenAPI specification' },
      { status: 500 },
    )
  }
}
