/**
 * Cloudflare Worker entry — wraps the OpenNext-generated handler with
 * Sentry's `withSentry` so every uncaught error in the Worker fetch
 * lifecycle (including the global `afterError` Payload hook wired in
 * `src/plugins/sentry/sentryPlugin.ts`) actually reaches Sentry.
 *
 * Without this wrapper, `@sentry/cloudflare`'s `Sentry.captureException`
 * is a silent no-op because no SDK client is attached to the request
 * context. The wrapper initializes the client per request, scoped to the
 * env-provided DSN.
 *
 * Wrangler resolves `../.open-next/worker.js` at deploy time — the file
 * is generated by `opennextjs-cloudflare build` (invoked from the
 * `[build]` section of `wrangler.toml`). TypeScript can't see it at
 * lint/type-check time, hence the `@ts-ignore` on the imports.
 *
 * Durable Object classes (`DOQueueHandler`, etc.) are re-exported to
 * preserve OpenNext's export surface — wrangler will pick them up if any
 * `[[durable_objects.bindings]]` is added in the future.
 */
import * as Sentry from '@sentry/cloudflare'

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - resolved by wrangler at deploy time (.open-next/ is git-ignored; absent in CI before build)
import opennextHandler from '../.open-next/worker.js'

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - resolved by wrangler at deploy time
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from '../.open-next/worker.js'

export default Sentry.withSentry<CloudflareEnv>(
  (env) => ({
    dsn: env.NEXT_PUBLIC_SENTRY_DSN,
    environment: env.NODE_ENV,
    // Errors only — no perf traces, mirrors src/instrumentation-client.ts.
    tracesSampleRate: 0,
    // When DSN isn't configured (local dev, preview deploys without secret),
    // skip init entirely so captureException stays a no-op rather than
    // throwing on missing config.
    enabled: !!env.NEXT_PUBLIC_SENTRY_DSN,
  }),
  opennextHandler,
)
