import type { StatusGlobalSpec } from './spec'

/**
 * The shape phase-2's admin widget reads — same as the historical
 * statusConfig.json file. Generated by walking a `StatusGlobalSpec`.
 */
export interface StatusConfigJson {
  collections: Record<string, { tutorialLink: string | null }>
  groups: Record<string, { label: string; description: string }>
  checks: Record<string, { label: string; description: string }>
}

function sortByKey<T>(record: Record<string, T>): Record<string, T> {
  const sorted: Record<string, T> = {}
  for (const key of Object.keys(record).sort()) sorted[key] = record[key]
  return sorted
}

/**
 * Extract the static display metadata from a `StatusGlobalSpec`. Deterministic
 * — keys within each section sort alphabetically — so re-running the
 * generator only produces a `git diff` when the spec actually changed.
 *
 * Throws if two different groups declare the same `key`, or if two
 * sections give the same `key` different metadata. The spec is the
 * single source of truth, so these collisions are programming errors.
 */
export function extractStatusConfig<TConfig>(
  spec: StatusGlobalSpec<TConfig>,
): StatusConfigJson {
  const groups: Record<string, { label: string; description: string }> = {}
  const checks: Record<string, { label: string; description: string }> = {}

  for (const section of spec.sections) {
    for (const group of section.groups) {
      if (group.key in groups) {
        throw new Error(
          `extractStatusConfig: duplicate group key "${group.key}" — declared by more than one section/group.`,
        )
      }
      groups[group.key] = { label: group.label, description: group.description }
    }

    for (const [checkKey, meta] of Object.entries(section.checks)) {
      const existing = checks[checkKey]
      if (existing && (existing.label !== meta.label || existing.description !== meta.description)) {
        throw new Error(
          `extractStatusConfig: check key "${checkKey}" has conflicting metadata across sections.`,
        )
      }
      checks[checkKey] = { label: meta.label, description: meta.description }
    }
  }

  return {
    collections: sortByKey(spec.collections),
    groups: sortByKey(groups),
    checks: sortByKey(checks),
  }
}
